import numpy as np

AMPLITUDE_FRONTLEG = np.pi/6
FREQUENCY_FRONTLEG = 4
PHASEOFFSET_FRONTLEG = np.pi/2

AMPLITUDE_BACKLEG = np.pi/4
FREQUENCY_BACKLEG = 4
PHASEOFFSET_BACKLEG = 0

numberOfGenerations = 10